apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner-mq
  namespace: default
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner-mq
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner-mq
    spec:
      serviceAccountName: nfs-client-provisioner-mq
      containers:
        - name: nfs-client-provisioner-mq
          image: luyou88/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.30.10.150 
            - name: NFS_PATH
              value: /stroageclass/dev-k8s-rabbitmq
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.30.10.150
            path: /stroageclass/dev-k8s-rabbitmq
